using System;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;
using SqlSugar;

namespace TaiheSystem.CBE.Api.Model
{
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author Taihe
// </auto-generated>
//------------------------------------------------------------------------------


    [SugarTable("Biz_PreContract")]
    public partial class Biz_PreContract
    {
           public Biz_PreContract(){

            this.ID =Guid.NewGuid().ToString();
            this.CreateTime =DateTime.Now;
            this.Status =Convert.ToInt32("0");

           }
           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : newid()
           /// </summary>
           [Display(Name = "")]           
           [SugarColumn(IsPrimaryKey=true)]
           public string ID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           [SugarColumn(IsIdentity=true)]
           public int PreContractID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string oaid {get;set;}

           /// <summary>
           /// 描述 : 合同编号 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "合同编号")]           
           public string ContractNo {get;set;}

           /// <summary>
           /// 描述 : 业务归属ID 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "业务归属ID")]           
           public string ServiceTypeID {get;set;}

           /// <summary>
           /// 描述 : 业务归属 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "业务归属")]           
           public string ServiceTypeName {get;set;}

           /// <summary>
           /// 描述 : 服务线 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "服务线")]           
           public string ServiceLine {get;set;}

           /// <summary>
           /// 描述 : 服务项目 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "服务项目")]           
           public string ServiceItem {get;set;}

           /// <summary>
           /// 描述 : 实收金额 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "实收金额")]           
           public decimal? ChargeFee {get;set;}

           /// <summary>
           /// 描述 : 客户id 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "客户id")]           
           public string khid {get;set;}

           /// <summary>
           /// 描述 : 客户名称 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "客户名称")]           
           public string khmc {get;set;}

           /// <summary>
           /// 描述 : 联系人 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "联系人")]           
           public string lxr {get;set;}

           /// <summary>
           /// 描述 : 联系电话 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "联系电话")]           
           public string lxdh {get;set;}

           /// <summary>
           /// 描述 : 创建时间 
           /// 空值 : True
           /// 默认 : DateTime.Now
           /// </summary>
           [Display(Name = "创建时间")]           
           public DateTime? CreateTime {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string CreateID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string CreateName {get;set;}

           /// <summary>
           /// 描述 : 0-未登记 1-已登记 
           /// 空值 : True
           /// 默认 : 0
           /// </summary>
           [Display(Name = "0-未登记 1-已登记")]           
           public int? Status {get;set;}

           /// <summary>
           /// 描述 : 登记时间 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "登记时间")]           
           public DateTime? RegisterTime {get;set;}

           /// <summary>
           /// 描述 : 登记人ID 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "登记人ID")]           
           public string RegisterID {get;set;}

           /// <summary>
           /// 描述 : 登记人姓名 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "登记人姓名")]           
           public string RegisterName {get;set;}

    }
}
