using System;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;
using SqlSugar;

namespace TaiheSystem.CBE.Api.Model
{
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author Taihe
// </auto-generated>
//------------------------------------------------------------------------------


    [SugarTable("Biz_Contract_Plan")]
    public partial class Biz_Contract_Plan
    {
           public Biz_Contract_Plan(){

            this.ID =Guid.NewGuid().ToString();
            this.status =Convert.ToInt32("30000");
            this.CreateTime =DateTime.Now;

           }
           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : newid()
           /// </summary>
           [Display(Name = "")]           
           [SugarColumn(IsPrimaryKey=true)]
           public string ID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           [SugarColumn(IsIdentity=true)]
           public int ContractPlanID {get;set;}

           /// <summary>
           /// 描述 : 客户id 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "客户id")]           
           public string CustomerID {get;set;}

           /// <summary>
           /// 描述 : 任务编号 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "任务编号")]           
           public string ContractPlanNo {get;set;}

           /// <summary>
           /// 描述 : 计划起始日期 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "计划起始日期")]           
           public DateTime? PlanStartDate {get;set;}

           /// <summary>
           /// 描述 : 计划结束日期 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "计划结束日期")]           
           public DateTime? PlanEndDate {get;set;}

           /// <summary>
           /// 描述 : 任务备注 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "任务备注")]           
           public string PlanRemark {get;set;}

           /// <summary>
           /// 描述 : 备注 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "备注")]           
           public string Remark {get;set;}

           /// <summary>
           /// 描述 : 状态 
           /// 空值 : True
           /// 默认 : 30000
           /// </summary>
           [Display(Name = "状态")]           
           public int? status {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : DateTime.Now
           /// </summary>
           [Display(Name = "")]           
           public DateTime? CreateTime {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string CreateID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string CreateName {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public DateTime? UpdateTime {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string UpdateID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string UpdateName {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public DateTime? SendSubmitTime {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string SendSubmitID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string SendSubmitName {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public DateTime? ApproveTime {get;set;}

           /// <summary>
           /// 描述 : 审批备注 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "审批备注")]           
           public string ApproveRemark {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string ApproveID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string ApproveName {get;set;}

    }
}
