using System;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;
using SqlSugar;

namespace TaiheSystem.CBE.Api.Model
{
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author Taihe
// </auto-generated>
//------------------------------------------------------------------------------


    [SugarTable("Biz_Contract_Plan_EvaluationProblem")]
    public partial class Biz_Contract_Plan_EvaluationProblem
    {
           public Biz_Contract_Plan_EvaluationProblem(){

            this.ID =Guid.NewGuid().ToString();
            this.status =Convert.ToInt32("0");

           }
           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : newid()
           /// </summary>
           [Display(Name = "")]           
           [SugarColumn(IsPrimaryKey=true)]
           public string ID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           [SugarColumn(IsIdentity=true)]
           public int AutoID {get;set;}

           /// <summary>
           /// 描述 : 计划任务ID 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "计划任务ID")]           
           public string ContractPlanID {get;set;}

           /// <summary>
           /// 描述 : 审核员ID 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "审核员ID")]           
           public string PlanAuditorID {get;set;}

           /// <summary>
           /// 描述 : 问题级别选项index 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "问题级别选项index")]           
           public int? ProblemLevelIndex {get;set;}

           /// <summary>
           /// 描述 : 问题级别名称 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "问题级别名称")]           
           public string ProblemLevelName {get;set;}

           /// <summary>
           /// 描述 : 审核员名称 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "审核员名称")]           
           public string UserName {get;set;}

           /// <summary>
           /// 描述 : 问题标题选项index 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "问题标题选项index")]           
           public int? ProblemTitleIndex {get;set;}

           /// <summary>
           /// 描述 : 问题标题名称 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "问题标题名称")]           
           public string ProblemTitleName {get;set;}

           /// <summary>
           /// 描述 : 问题内容 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "问题内容")]           
           public string ProblemContent {get;set;}

        /// <summary>
        /// 描述 : 问题回复 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "问题回复")]
        public string ProblemRespond { get; set; }

        /// <summary>
        /// 描述 : 文件ID 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "文件ID")]           
           public string ProblemFileID {get;set;}

           /// <summary>
           /// 描述 : 0-未整改 1-已整改 
           /// 空值 : True
           /// 默认 : 0
           /// </summary>
           [Display(Name = "0-未整改 1-已整改")]           
           public int? status {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public DateTime? CreateTime {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string CreateID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string CreateName {get;set;}

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "")]
        public DateTime? UpdateTime { get; set; }

    }
}
