using System;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;
using SqlSugar;

namespace TaiheSystem.CBE.Api.Model
{
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author Taihe
// </auto-generated>
//------------------------------------------------------------------------------


    [SugarTable("Biz_Contract_PlanAuditor_Draw")]
    public partial class Biz_Contract_PlanAuditor_Draw
    {
           public Biz_Contract_PlanAuditor_Draw(){

            this.ID =Guid.NewGuid().ToString();
            this.CreateTime =DateTime.Now;

           }
           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : newid()
           /// </summary>
           [Display(Name = "")]           
           [SugarColumn(IsPrimaryKey=true)]
           public string ID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           [SugarColumn(IsIdentity=true)]
           public int PlanDrawID {get;set;}

           /// <summary>
           /// 描述 : 审核员项目项目ID 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "审核员项目项目ID")]           
           public string PlanAuditorItemID {get;set;}

           /// <summary>
           /// 描述 : 计划开始时间 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "计划开始时间")]           
           public DateTime? DrawStartTime {get;set;}

           /// <summary>
           /// 描述 : 计划结束时间 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "计划结束时间")]           
           public DateTime? DrawEndTime {get;set;}

           /// <summary>
           /// 描述 : 部门 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "部门")]           
           public string Department {get;set;}

           /// <summary>
           /// 描述 : 计划内容 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "计划内容")]           
           public string DrawContent {get;set;}

           /// <summary>
           /// 描述 : 条款 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "条款")]           
           public string DrawClause {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : DateTime.Now
           /// </summary>
           [Display(Name = "")]           
           public DateTime? CreateTime {get;set;}

    }
}
