using System;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;
using SqlSugar;

namespace TaiheSystem.CBE.Api.Model
{
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author Taihe
// </auto-generated>
//------------------------------------------------------------------------------


    [SugarTable("Cfg_SystemType")]
    public partial class Cfg_SystemType
    {
           public Cfg_SystemType(){

            this.ID =Guid.NewGuid().ToString();

           }
           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : newid()
           /// </summary>
           [Display(Name = "")]           
           [SugarColumn(IsPrimaryKey=true)]
           public string ID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           [SugarColumn(IsIdentity=true)]
           public int TypeID {get;set;}

           /// <summary>
           /// 描述 : 类别编码 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "类别编码")]           
           public string TypeCode {get;set;}

           /// <summary>
           /// 描述 : 体系类别名称 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "体系类别名称")]           
           public string TypeName {get;set;}

           /// <summary>
           /// 描述 : 英文名称 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "英文名称")]           
           public string TypeNameEN {get;set;}

           /// <summary>
           /// 描述 : 说明 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "说明")]           
           public string TypeNameDescr {get;set;}

           /// <summary>
           /// 描述 : 是否启用 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "是否启用")]           
           public bool? Enabled {get;set;}

           /// <summary>
           /// 描述 : 序号 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "序号")]           
           public int? SortIndex {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public DateTime? CreateTime {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string CreateID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string CreateName {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public DateTime? UpdateTime {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string UpdateID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string UpdateName {get;set;}

    }
}
