using System;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;
using SqlSugar;

namespace TaiheSystem.CBE.Api.Model
{
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author Taihe
// </auto-generated>
//------------------------------------------------------------------------------


    [SugarTable("Cfg_ServiceType")]
    public partial class Cfg_ServiceType
    {
           public Cfg_ServiceType(){

            this.ID =Guid.NewGuid().ToString();
            this.CreateTime =DateTime.Now;

           }
           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : newid()
           /// </summary>
           [Display(Name = "")]           
           [SugarColumn(IsPrimaryKey=true)]
           public string ID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           [SugarColumn(IsIdentity=true)]
           public int AutoID {get;set;}

           /// <summary>
           /// 描述 : 业务归属名称 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "业务归属名称")]           
           public string ServiceTypeName {get;set;}

           /// <summary>
           /// 描述 : 业务归属代码 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "业务归属代码")]           
           public string ServiceTypeCode {get;set;}

           /// <summary>
           /// 描述 : 父级ID 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "父级ID")]           
           public string ParentUID {get;set;}

           /// <summary>
           /// 描述 : 排序 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "排序")]           
           public int? SortIndex {get;set;}

           /// <summary>
           /// 描述 : 备注 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "备注")]           
           public string remark {get;set;}

           /// <summary>
           /// 描述 : 添加时间 
           /// 空值 : True
           /// 默认 : DateTime.Now
           /// </summary>
           [Display(Name = "添加时间")]           
           public DateTime? CreateTime {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string CreateID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string CreateName {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public DateTime? UpdateTime {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string UpdateID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string UpdateName {get;set;}

    }
}
