using System;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;
using SqlSugar;

namespace TaiheSystem.CBE.Api.Model
{
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author Taihe
// </auto-generated>
//------------------------------------------------------------------------------


    [SugarTable("Doc_TMPTYPE")]
    public partial class Doc_TMPTYPE
    {
           public Doc_TMPTYPE(){

            this.ID =Guid.NewGuid().ToString();
            this.CreateTime =DateTime.Now;
            this.deleted =false;
            this.ParentUID = null;
           }
           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : newid()
           /// </summary>
           [Display(Name = "")]           
           [SugarColumn(IsPrimaryKey=true)]
           public string ID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           [SugarColumn(IsIdentity=true)]
           public int AutoID {get;set;}

           /// <summary>
           /// 描述 : 类别代号 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "类别代号")]           
           public string TMPTypeCode {get;set;}

           /// <summary>
           /// 描述 : 类别名称 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "类别名称")]           
           public string TMPTypeName {get;set;}

           /// <summary>
           /// 描述 : 类别说明 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "类别说明")]           
           public string Remark {get;set;}

           /// <summary>
           /// 描述 : 父级类别ID 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "父级类别ID")]           
           public string ParentUID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : DateTime.Now
           /// </summary>
           [Display(Name = "")]           
           public DateTime? CreateTime {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string CreateID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string CreateName {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public DateTime? UpdateTime {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string UpdateID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string UpdateName {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 0
           /// </summary>
           [Display(Name = "")]           
           public bool? deleted {get;set;}

           /// <summary>
           /// 描述 : 序号 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "序号")]           
           public int? SortIndex {get;set;}

    }
}
