using System;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;
using SqlSugar;

namespace TaiheSystem.CBE.Api.Model
{
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author Taihe
// </auto-generated>
//------------------------------------------------------------------------------


    [SugarTable("Gwf_Operation")]
    public partial class Gwf_Operation
    {
           public Gwf_Operation(){


           }
           /// <summary>
           /// 描述 : 模块ID 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "模块ID")]           
           public string FlowCode {get;set;}

           /// <summary>
           /// 描述 : 流程编号 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "流程编号")]           
           public string OperationCode {get;set;}

           /// <summary>
           /// 描述 : 流程名称 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "流程名称")]           
           public string OperationName {get;set;}

           /// <summary>
           /// 描述 : 流程起 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "流程起")]           
           public string Node_From {get;set;}

           /// <summary>
           /// 描述 : 流程止 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "流程止")]           
           public string Node_To {get;set;}

           /// <summary>
           /// 描述 : 后置操作 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "后置操作")]           
           public string AfterDone {get;set;}

           /// <summary>
           /// 描述 : 撤销后置操作 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "撤销后置操作")]           
           public string CancelledDone {get;set;}

           /// <summary>
           /// 描述 : 说明 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "说明")]           
           public string Remark {get;set;}

    }
}
