using System;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;
using SqlSugar;

namespace TaiheSystem.CBE.Api.Model
{
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author Taihe
// </auto-generated>
//------------------------------------------------------------------------------


    [SugarTable("Gwf_Step")]
    public partial class Gwf_Step
    {
           public Gwf_Step(){


           }
           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           [SugarColumn(IsPrimaryKey=true,IsIdentity=true)]
           public int ID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string FlowCode {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string OperationCode {get;set;}

           /// <summary>
           /// 描述 : 流程开始 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "流程开始")]           
           public string Node_From {get;set;}

           /// <summary>
           /// 描述 : 流程目标 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "流程目标")]           
           public string Node_To {get;set;}

           /// <summary>
           /// 描述 : 操作说明 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "操作说明")]           
           public string StepRemark {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public DateTime? CreateTime {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string CreateID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string CreateName {get;set;}

           /// <summary>
           /// 描述 : 合同ID 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "合同ID")]           
           public string Biz_MainContract_ID {get;set;}

           /// <summary>
           /// 描述 : 任务ID 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "任务ID")]           
           public string Biz_Contract_Plan_ID {get;set;}

           /// <summary>
           /// 描述 : 项目ID 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "项目ID")]           
           public string Biz_ContractItem_Sub_ID {get;set;}

           /// <summary>
           /// 描述 : 审核员ID 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "审核员ID")]           
           public string Biz_Contract_PlanAuditor_ID {get;set;}

    }
}
