using System;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;
using SqlSugar;

namespace TaiheSystem.CBE.Api.Model
{
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author Taihe
// </auto-generated>
//------------------------------------------------------------------------------


    [SugarTable("Org_Department")]
    public partial class Org_Department
    {
           public Org_Department(){

            this.CreateTime =DateTime.Now;

           }
           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           [SugarColumn(IsPrimaryKey=true)]
           public string ID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           [SugarColumn(IsIdentity=true)]
           public int AutoID {get;set;}

           /// <summary>
           /// 描述 : 部门编号 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "部门编号")]           
           public string DeptNo {get;set;}

           /// <summary>
           /// 描述 : 部门名称 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "部门名称")]           
           public string DeptName {get;set;}

           /// <summary>
           /// 描述 : 部门简称 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "部门简称")]           
           public string DeptAbbreviation {get;set;}

           /// <summary>
           /// 描述 : 父级部门ID 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "父级部门ID")]           
           public string ParentUID {get;set;}

           /// <summary>
           /// 描述 : 部门说明 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "部门说明")]           
           public string DeptDescr {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : DateTime.Now
           /// </summary>
           [Display(Name = "")]           
           public DateTime? CreateTime {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string CreateID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string CreateName {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public DateTime? UpdateTime {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string UpdateID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string UpdateName {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string oid {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public int? SortIndex {get;set;}

    }
}
