using System;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;
using SqlSugar;

namespace TaiheSystem.CBE.Api.Model
{
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author Taihe
// </auto-generated>
//------------------------------------------------------------------------------


    [SugarTable("Sys_User_Classification")]
    public partial class Sys_User_Classification
    {
           public Sys_User_Classification(){

            this.ID =Guid.NewGuid().ToString();
            this.CreateTime =DateTime.Now;

           }
           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : newid()
           /// </summary>
           [Display(Name = "")]           
           [SugarColumn(IsPrimaryKey=true)]
           public string ID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           [SugarColumn(IsIdentity=true)]
           public int AutoID {get;set;}

           /// <summary>
           /// 描述 : 注册资格ID 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "注册资格ID")]           
           public string UserSystemTypeID {get;set;}

           /// <summary>
           /// 描述 : 用户ID 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "用户ID")]           
           public string UserID {get;set;}

           /// <summary>
           /// 描述 : 专业代码ID 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "专业代码ID")]           
           public string BizClassificationID {get;set;}

           /// <summary>
           /// 描述 : 专业代码 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "专业代码")]           
           public string ClassificationCode {get;set;}

           /// <summary>
           /// 描述 : 能力来源选项index 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "能力来源选项index")]           
           public int? AbilityTypeIndex {get;set;}

           /// <summary>
           /// 描述 : 能力来源名称 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "能力来源名称")]           
           public string AbilityTypeName {get;set;}

           /// <summary>
           /// 描述 : 评定人员ID 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "评定人员ID")]           
           public string AccessPersonID {get;set;}

           /// <summary>
           /// 描述 : 评定人员名称 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "评定人员名称")]           
           public string AccessPersonName {get;set;}

           /// <summary>
           /// 描述 : 通过日期 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "通过日期")]           
           public DateTime? PassDate {get;set;}

           /// <summary>
           /// 描述 : 备注 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "备注")]           
           public string Remark {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : DateTime.Now
           /// </summary>
           [Display(Name = "")]           
           public DateTime? CreateTime {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string CreateID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string CreateName {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public DateTime? UpdateTime {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string UpdateID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string UpdateName {get;set;}

    }
}
