using System;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;
using SqlSugar;

namespace TaiheSystem.CBE.Api.Model
{
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author Taihe
// </auto-generated>
//------------------------------------------------------------------------------


    [SugarTable("Sys_User_SystemType")]
    public partial class Sys_User_SystemType
    {
           public Sys_User_SystemType(){

            this.ID =Guid.NewGuid().ToString();
            this.CreateTime =DateTime.Now;
            this.UpdateTime =DateTime.Now;

           }
           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : newid()
           /// </summary>
           [Display(Name = "")]           
           [SugarColumn(IsPrimaryKey=true)]
           public string ID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           [SugarColumn(IsIdentity=true)]
           public int UserSystemTypeID {get;set;}

           /// <summary>
           /// 描述 : 用户ID 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "用户ID")]           
           public string UserID {get;set;}

           /// <summary>
           /// 描述 : 体系类别ID 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "体系类别ID")]           
           public string SystemTypeID {get;set;}

           /// <summary>
           /// 描述 : 体系类别Code 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "体系类别Code")]           
           public string SystemTypeCode {get;set;}

           /// <summary>
           /// 描述 : 体系类别名称 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "体系类别名称")]           
           public string SystemTypeName {get;set;}

           /// <summary>
           /// 描述 : 标准名称 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "标准名称")]           
           public string StandardNames {get;set;}

           /// <summary>
           /// 描述 : 标准日期 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "标准日期")]           
           public DateTime? StandardDate {get;set;}

           /// <summary>
           /// 描述 : 注册资格选项index 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "注册资格选项index")]           
           public int? QualificationTypeID {get;set;}

           /// <summary>
           /// 描述 : 注册资格选项名称 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "注册资格选项名称")]           
           public string QualificationTypeName {get;set;}

           /// <summary>
           /// 描述 : 资格注册号 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "资格注册号")]           
           public string RegisterQualificationNo {get;set;}

           /// <summary>
           /// 描述 : 开始时间 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "开始时间")]           
           public DateTime? QualificationStartDate {get;set;}

           /// <summary>
           /// 描述 : 结束时间 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "结束时间")]           
           public DateTime? QualificationEndedDate {get;set;}

           /// <summary>
           /// 描述 : 组长与否:0-否 1-组长 2-见习组织 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "组长与否:0-否 1-组长 2-见习组织")]           
           public int? GroupLeaderType {get;set;}

           /// <summary>
           /// 描述 : 能否做见证 0-无 1-内部见证 2-外部见证 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "能否做见证 0-无 1-内部见证 2-外部见证")]           
           public int? WitnessType {get;set;}

           /// <summary>
           /// 描述 : 备注 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "备注")]           
           public string Remark {get;set;}

           /// <summary>
           /// 描述 : 暂停资格 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "暂停资格")]           
           public bool? Enabled {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : DateTime.Now
           /// </summary>
           [Display(Name = "")]           
           public DateTime? CreateTime {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string CreateID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string CreateName {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : DateTime.Now
           /// </summary>
           [Display(Name = "")]           
           public DateTime? UpdateTime {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string UpdateID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string UpdateName {get;set;}

    }
}
