using System;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;
using SqlSugar;

namespace TaiheSystem.CBE.Api.Model
{
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author Taihe
// </auto-generated>
//------------------------------------------------------------------------------


    [SugarTable("uf_khxx_dt1")]
    public partial class uf_khxx_dt1
    {
           public uf_khxx_dt1(){

            this.ID =Guid.NewGuid().ToString();

           }
           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : newid()
           /// </summary>
           [Display(Name = "")]           
           [SugarColumn(IsPrimaryKey=true)]
           public string ID {get;set;}

           /// <summary>
           /// 描述 : 所属客户ID 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "所属客户ID")]           
           public string ParentUID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public int? oaid {get;set;}

           /// <summary>
           /// 描述 : 所属客户oaid 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "所属客户oaid")]           
           public int? mainid {get;set;}

           /// <summary>
           /// 描述 : 联系人 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "联系人")]           
           public string lxr {get;set;}

           /// <summary>
           /// 描述 : 部门 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "部门")]           
           public string bm {get;set;}

           /// <summary>
           /// 描述 : 职务 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "职务")]           
           public string zw {get;set;}

           /// <summary>
           /// 描述 : 座机 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "座机")]           
           public string zj {get;set;}

           /// <summary>
           /// 描述 : 手机 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "手机")]           
           public string sj {get;set;}

           /// <summary>
           /// 描述 : 邮箱 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "邮箱")]           
           public string yx {get;set;}

           /// <summary>
           /// 描述 : 备注 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "备注")]           
           public string bz {get;set;}

           /// <summary>
           /// 描述 : 添加时间 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "添加时间")]           
           public DateTime? CreateTime {get;set;}

           /// <summary>
           /// 描述 : 更新时间 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "更新时间")]           
           public DateTime? UpdateTime {get;set;}

    }
}
