using System;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;
using SqlSugar;

namespace TaiheSystem.CBE.Api.Model
{
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author Taihe
// </auto-generated>
//------------------------------------------------------------------------------


    [SugarTable("uf_khxx")]
    public partial class uf_khxx
    {
           public uf_khxx(){

            this.ID =Guid.NewGuid().ToString();
            this.CreateTime =DateTime.Now;

           }
           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : newid()
           /// </summary>
           [Display(Name = "")]           
           [SugarColumn(IsPrimaryKey=true)]
           public string ID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           [SugarColumn(IsIdentity=true)]
           public int khxxID {get;set;}

           /// <summary>
           /// 描述 : od主键 
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "od主键")]           
           public int odid {get;set;}

           /// <summary>
           /// 描述 : 分公司所属总公司ID 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "分公司所属总公司ID")]           
           public string ParentUID {get;set;}

           /// <summary>
           /// 描述 : 统一信用代码 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "统一信用代码")]           
           public string tyxydm {get;set;}

           /// <summary>
           /// 描述 : 分公司(部门ID) 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "分公司(部门ID)")]           
           public string fgs {get;set;}

           /// <summary>
           /// 描述 : 合作伙伴ID 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "合作伙伴ID")]           
           public string hzdwID {get;set;}

           /// <summary>
           /// 描述 : 合作伙伴编码 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "合作伙伴编码")]           
           public string hzdw {get;set;}

           /// <summary>
           /// 描述 : 合作伙伴名称 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "合作伙伴名称")]           
           public string hzdwmc {get;set;}

           /// <summary>
           /// 描述 : 企业编码 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "企业编码")]           
           public string qybm {get;set;}

           /// <summary>
           /// 描述 : 是否规模以上企业 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "是否规模以上企业")]           
           public int? gmysqy {get;set;}

           /// <summary>
           /// 描述 : 组织名称 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "组织名称")]           
           public string zzmc {get;set;}

           /// <summary>
           /// 描述 : 英文名称 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "英文名称")]           
           public string ywmc {get;set;}

           /// <summary>
           /// 描述 : 组织原名 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "组织原名")]           
           public string zzym {get;set;}

           /// <summary>
           /// 描述 : 客户级别(A B C D ) 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "客户级别(A B C D )")]           
           public int? khjb {get;set;}

           /// <summary>
           /// 描述 : 组织电话 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "组织电话")]           
           public string zzdh {get;set;}

           /// <summary>
           /// 描述 : 组织传真 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "组织传真")]           
           public string zzcz {get;set;}

           /// <summary>
           /// 描述 : 组织邮箱 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "组织邮箱")]           
           public string zzyx {get;set;}

           /// <summary>
           /// 描述 : 国家/地区代码 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "国家/地区代码")]           
           public int? gjdqdm {get;set;}

           /// <summary>
           /// 描述 : 法人代表 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "法人代表")]           
           public string frdb {get;set;}

           /// <summary>
           /// 描述 : 企业人数 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "企业人数")]           
           public int? qyrs {get;set;}

           /// <summary>
           /// 描述 : 业务员(人员ID) 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "业务员(人员ID)")]           
           public string ywy {get;set;}

           /// <summary>
           /// 描述 : 客服人员(人员ID) 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "客服人员(人员ID)")]           
           public string kfry {get;set;}

           /// <summary>
           /// 描述 : 注册资本 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "注册资本")]           
           public string zczb {get;set;}

           /// <summary>
           /// 描述 : 货币单位(选项ID) 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "货币单位(选项ID)")]           
           public int? hbdw {get;set;}

           /// <summary>
           /// 描述 : 行政区划(选项ID) 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "行政区划(选项ID)")]           
           public int? xzqh {get;set;}

           /// <summary>
           /// 描述 : 行政区划名称 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "行政区划名称")]           
           public string xzqhmc {get;set;}

           /// <summary>
           /// 描述 : 区划代码 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "区划代码")]           
           public string qhdm {get;set;}

           /// <summary>
           /// 描述 : 注册地址 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "注册地址")]           
           public string zcdz {get;set;}

           /// <summary>
           /// 描述 : 英文地址 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "英文地址")]           
           public string ywdz {get;set;}

           /// <summary>
           /// 描述 : 邮编 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "邮编")]           
           public string ybzc {get;set;}

           /// <summary>
           /// 描述 : 办公通讯地址 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "办公通讯地址")]           
           public string bgtxdz {get;set;}

           /// <summary>
           /// 描述 : 办公通讯英文 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "办公通讯英文")]           
           public string bgtxyw {get;set;}

           /// <summary>
           /// 描述 : 邮编（办公） 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "邮编（办公）")]           
           public string ybbg {get;set;}

           /// <summary>
           /// 描述 : 经营地址 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "经营地址")]           
           public string jydz {get;set;}

           /// <summary>
           /// 描述 : 经营英文 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "经营英文")]           
           public string jyyw {get;set;}

           /// <summary>
           /// 描述 : 邮编(经营) 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "邮编(经营)")]           
           public string ybjy {get;set;}

           /// <summary>
           /// 描述 : 开票类型(选项ID) 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "开票类型(选项ID)")]           
           public string kplx {get;set;}

           /// <summary>
           /// 描述 : 公司税号 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "公司税号")]           
           public string gssh {get;set;}

           /// <summary>
           /// 描述 : 开户名称 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "开户名称")]           
           public string khmc {get;set;}

           /// <summary>
           /// 描述 : 开户地址 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "开户地址")]           
           public string khdz {get;set;}

           /// <summary>
           /// 描述 : 开户电话 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "开户电话")]           
           public string khdh {get;set;}

           /// <summary>
           /// 描述 : 开户银行 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "开户银行")]           
           public string khyx {get;set;}

           /// <summary>
           /// 描述 : 银行账号 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "银行账号")]           
           public string yxzh {get;set;}

           /// <summary>
           /// 描述 : 开票备注 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "开票备注")]           
           public string kpbz {get;set;}

           /// <summary>
           /// 描述 : 最高管理者 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "最高管理者")]           
           public string zgglz {get;set;}

           /// <summary>
           /// 描述 : 最高管理者手机号 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "最高管理者手机号")]           
           public string zgglzsjh {get;set;}

           /// <summary>
           /// 描述 : 管理者代表 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "管理者代表")]           
           public string glzdb {get;set;}

           /// <summary>
           /// 描述 : 手机号 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "手机号")]           
           public string sjh {get;set;}

           /// <summary>
           /// 描述 : 经度 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "经度")]           
           public string jd {get;set;}

           /// <summary>
           /// 描述 : 纬度 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "纬度")]           
           public string wd {get;set;}

           /// <summary>
           /// 描述 : 组织网站 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "组织网站")]           
           public string zzwz {get;set;}

           /// <summary>
           /// 描述 : 经营范围 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "经营范围")]           
           public string jyfw {get;set;}

           /// <summary>
           /// 描述 : 备注信息 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "备注信息")]           
           public string bzxx {get;set;}

           /// <summary>
           /// 描述 : 主要产品 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "主要产品")]           
           public string zycp {get;set;}

           /// <summary>
           /// 描述 : 主要客户 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "主要客户")]           
           public string zykh {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string zzxz {get;set;}

           /// <summary>
           /// 描述 : 统一信用代码 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "统一信用代码")]           
           public string tyxydmwb {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public int? sf {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public int? cs {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public int? quxian {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string zzxzzw {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string sfzw {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string cssfzw {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string qxsfzw {get;set;}

           /// <summary>
           /// 描述 : 最高管理者座机 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "最高管理者座机")]           
           public string zgglzzj {get;set;}

           /// <summary>
           /// 描述 : 最高管理者邮箱 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "最高管理者邮箱")]           
           public string zgglzyx {get;set;}

           /// <summary>
           /// 描述 : 主公司名称 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "主公司名称")]           
           public string zgsmc {get;set;}

           /// <summary>
           /// 描述 : 是否开通账号 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "是否开通账号")]           
           public int? sfktzh {get;set;}

           /// <summary>
           /// 描述 : 部门(部门ID) 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "部门(部门ID)")]           
           public string bm {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : DateTime.Now
           /// </summary>
           [Display(Name = "")]           
           public DateTime? CreateTime {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public DateTime? UpdateTime {get;set;}

    }
}
