//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author Taihe
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;
using System.Linq;
using System.Text;
using SqlSugar;


namespace TaiheSystem.CBE.Api.Model.View
{
    public class CustomerVM
    {

           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : newid()
           /// </summary>
           [Display(Name = "")]           
           public string ID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public int oaid {get;set;}

           /// <summary>
           /// 描述 : 编码 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "编码")]           
           public string qybm { get;set;}

           /// <summary>
           /// 描述 : 组织名称
            /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "组织名称")]           
           public string zzmc { get;set;}

           /// <summary>
           /// 描述 : 行政区划 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "行政区划")]           
           public string xzqhmc { get;set;}

           /// <summary>
           /// 描述 : 分公司 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "分公司")]           
           public string fgs { get;set;}

           /// <summary>
           /// 描述 : 业务员 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "业务员")]           
           public string ywy { get;set;}

           /// <summary>
           /// 描述 : 合作单位名称 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "合作单位名称")]           
           public string hzdwmc { get;set;}


            /// <summary>
            /// 描述 : 联系人
            /// 空值 : True
            /// 默认 : 
            /// </summary>
            [Display(Name = "联系人")]
            public string lxr { get; set; }


            /// <summary>
            /// 描述 : 手机
            /// 空值 : True
            /// 默认 : 
            /// </summary>
            [Display(Name = "手机")]
            public string sj { get; set; }


            /// <summary>
            /// 描述 : 邮箱
            /// 空值 : True
            /// 默认 : 
            /// </summary>
            [Display(Name = "邮箱")]
            public string yx { get; set; }

            /// <summary>
            /// 描述 : 组织电话
            /// 空值 : True
            /// 默认 : 
            /// </summary>
            [Display(Name = "组织电话")]           
           public string zzdh { get;set;}

           /// <summary>
           /// 描述 : 组织传真
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "组织传真")]           
           public string zzcz { get;set;}

           /// <summary>
           /// 描述 : 企业人数 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "企业人数")]           
           public int? qyrs { get;set;}

    }
}