//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author Taihe
// </auto-generated>
//------------------------------------------------------------------------------
using TaiheSystem.CBE.Api.Model;
using TaiheSystem.CBE.Api.Model.Dto;
using TaiheSystem.CBE.Api.Model.View;
using System.Collections.Generic;
using System.Threading.Tasks;
using SqlSugar;
using System.Linq;

namespace TaiheSystem.CBE.Api.Interfaces
{
    public interface IufkhxxService : IBaseService<uf_khxx>
    {

        #region CustomInterface 
        /// <summary>
        /// 查询客户列表（分页）
        /// </summary>
        /// <param name="parm"></param>
        /// <returns></returns>
        PagedInfo<CustomerVM> QueryCustomerPages(CustomerQueryDto parm);
        #endregion

    }
}
