//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author Taihe
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;
using System.Linq;
using System.Text;
using SqlSugar;


namespace TaiheSystem.CBE.Api.Model.View.Main
{
    /// <summary>
    /// 合同上传附件信息
    /// </summary>
    public class ContractFileVM
    {

        /// <summary>
        /// 描述 : UUID 
        /// 空值 : False
        /// 默认 : 
        /// </summary>
        [Display(Name = "UUID")]
        public string ID { get; set; }

        /// <summary>
        /// 描述 : 合同ID 
        /// 空值 : False
        /// 默认 : 
        /// </summary>
        [Display(Name = "合同ID")]
        public string MainContractID { get; set; }

        /// <summary>
        /// 描述 : 主公司 
        /// 空值 : False
        /// 默认 : 
        /// </summary>
        [Display(Name = "主公司")]
        public string CustomerUID { get; set; }


        /// <summary>
        /// 描述 : 文件ID 
        /// 空值 : False
        /// 默认 : 
        /// </summary>
        [Display(Name = "文件id")]
        public string FileID { get; set; }

        /// <summary>
        /// 描述 : 文件名称
        /// 空值 : False
        /// 默认 : 
        /// </summary>
        [Display(Name = "文件名称")]
        public string FileName { get; set; }
    }
}