//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author Taihe
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;
using System.Linq;
using System.Text;
using SqlSugar;
using System.Collections.Generic;

namespace TaiheSystem.CBE.Api.Model.View.Main
{
    /// <summary>
    /// 合同项目信息
    /// </summary>
    public class ContractItemVM
    {

        /// <summary>
        /// 描述 : UUID 
        /// 空值 : False
        /// 默认 : 
        /// </summary>
        [Display(Name = "UUID")]
        public string ID { get; set; }

        /// <summary>
        /// 描述 : 合同ID 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "合同ID")]
        public string MainContractID { get; set; }

        /// <summary>
        /// 描述 : 项目编号 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "项目编号")]
        public string ContractItemNo { get; set; }

        /// <summary>
        /// 描述 : 项目标准ID 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "项目标准ID")]
        public string ItemStandardID { get; set; }

        /// <summary>
        /// 描述 : 项目编号 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "项目编号")]
        public string ItemStandardCode { get; set; }

        /// <summary>
        /// 描述 : 项目名称 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "项目名称")]
        public string ItemName { get; set; }

        /// <summary>
        /// 描述 : 审核类型ID 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "审核类型ID")]
        public string AuditTypeID { get; set; }

        /// <summary>
        /// 描述 : 审核类型名称 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "审核类型名称")]
        public string AuditTypeName { get; set; }

        /// <summary>
        /// 描述 : 体系人数 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "体系人数")]
        public int? PropleNum { get; set; }

        /// <summary>
        /// 描述 : 申请范围 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "申请范围")]
        public string ApplyRange { get; set; }

        /// <summary>
        /// 描述 : 申请范围(英文) 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "申请范围(英文)")]
        public string ApplyRangeEN { get; set; }

        /// <summary>
        /// 描述 : 复评次数 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "复评次数")]
        public string ReevaluateNum { get; set; }

        /// <summary>
        /// 描述 : 是否机构转入 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "是否机构转入")]
        public bool? OrganizationIn { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "")]
        public DateTime? CreateTime { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "")]
        public string CreateID { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "")]
        public string CreateName { get; set; }

        /// <summary>
        /// 描述 : 0-否 1-是 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "0-否 1-是")]
        public int? deleted { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "")]
        public DateTime? UpdateTime { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "")]
        public string UpdateID { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "")]
        public string UpdateName { get; set; }

        /// <summary>
        /// 描述 : 一阶段是否现场 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "一阶段是否现场")]
        public bool? IsSiteWork { get; set; }

        /// <summary>
        /// 描述 : 非现场原因选项Index 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "非现场原因选项Index")]
        public int? NotSiteWorkReasonID { get; set; }

        /// <summary>
        /// 描述 : 非现场原因 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "非现场原因")]
        public string NotSiteWorkReason { get; set; }

        /// <summary>
        /// 描述 : 风险等级选项Index 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "风险等级选项Index")]
        public int? RiskRegisterID { get; set; }

        /// <summary>
        /// 描述 : 风险等级 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "风险等级")]
        public string RiskRegister { get; set; }

        /// <summary>
        /// 描述 : 不适用条款 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "不适用条款")]
        public string IncompatibilityClause { get; set; }

        /// <summary>
        /// 描述 : CNAS认可标志 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "CNAS认可标志")]
        public bool? CNAS { get; set; }

        /// <summary>
        /// 描述 : 评审范围 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "评审范围")]
        public string AuditScope { get; set; }

        /// <summary>
        /// 描述 : 评审范围英文 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "评审范围英文")]
        public string AuditScopeEN { get; set; }

        /// <summary>
        /// 描述 : 初审基础人日 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "初审基础人日")]
        public decimal? FirstTrialBaseDays { get; set; }

        /// <summary>
        /// 描述 : 监督基础人日 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "监督基础人日")]
        public decimal? SupervisionBaseDays { get; set; }

        /// <summary>
        /// 描述 : 再认证人日 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "再认证人日")]
        public decimal? RecertificationBaseDays { get; set; }

        /// <summary>
        /// 描述 : 初审总人日 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "初审总人日")]
        public decimal? FirstTrialTotalDays { get; set; }

        /// <summary>
        /// 描述 : 监督总人日 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "监督总人日")]
        public decimal? SupervisionTotalDays { get; set; }

        /// <summary>
        /// 描述 : 再认证总人日 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "再认证总人日")]
        public decimal? RecertificationTotalDays { get; set; }

        /// <summary>
        /// 描述 : 支持方式 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "支持方式")]
        public string SupportWay { get; set; }



        /// <summary>
        /// 增人日依据
        /// </summary>
        [Display(Name = "增人日依据")]
        public List<Biz_ContractItem_Add> ContractItemAddList;

        /// <summary>
        /// 增人日依据(新增)
        /// </summary>
        [Display(Name = "增人日依据（新增）")]
        public List<Biz_ContractItem_Add> ContractItemAddList_insert;

        /// <summary>
        /// 增人日依据(修改)
        /// </summary>
        [Display(Name = "增人日依据（修改）")]
        public List<Biz_ContractItem_Add> ContractItemAddList_update;

        /// <summary>
        /// 增人日依据(删除)
        /// </summary>
        [Display(Name = "增人日依据（删除）")]
        public List<Biz_ContractItem_Add> ContractItemAddList_delete;

        /// <summary>
        /// 减人日依据
        /// </summary>
        [Display(Name = "减人日依据")]
        public List<Biz_ContractItem_Minus> ContractItemMinusList;

        /// <summary>
        /// 减人日依据（新增）
        /// </summary>
        [Display(Name = "减人日依据（新增）")]
        public List<Biz_ContractItem_Minus> ContractItemMinusList_insert;

        /// <summary>
        /// 减人日依据（修改）
        /// </summary>
        [Display(Name = "减人日依据（修改）")]
        public List<Biz_ContractItem_Minus> ContractItemMinusList_update;

        /// <summary>
        /// 减人日依据（删除）
        /// </summary>
        [Display(Name = "减人日依据（删除）")]
        public List<Biz_ContractItem_Minus> ContractItemMinusList_delete;

        /// <summary>
        /// 专业代码
        /// </summary>
        [Display(Name = "专业代码")]
        public List<ContractItemBizClassVM> ContractItemBizClassificationList;

        /// <summary>
        /// 专业代码(新增)
        /// </summary>
        [Display(Name = "专业代码(新增)")]
        public List<ContractItemBizClassVM> ContractItemBizClassificationList_insert;

        /// <summary>
        /// 专业代码(修改)
        /// </summary>
        [Display(Name = "专业代码(修改)")]
        public List<ContractItemBizClassVM> ContractItemBizClassificationList_update;

        /// <summary>
        /// 专业代码(删除)
        /// </summary>
        [Display(Name = "专业代码(删除)")]
        public List<ContractItemBizClassVM> ContractItemBizClassificationList_delete;

    }
}