//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author Taihe
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;
using System.Linq;
using System.Text;
using SqlSugar;
using System.Collections.Generic;

namespace TaiheSystem.CBE.Api.Model.View.AuditPlan
{
    /// <summary>
    /// 审核员
    /// </summary>
    public class PlanAuditorItemVM
    {

        /// <summary>
        /// 描述 :  审核员标准ID
        /// 空值 : False
        /// 默认 : newid()
        /// </summary>
        [Display(Name = "审核员标准ID")]
        public string PlanAuditorItemID { get; set; }

        /// <summary>
        /// 描述 : 审核员ID
        /// 空值 : False
        /// 默认 : 
        /// </summary>
        [Display(Name = "审核员ID")]
        public string PlanAuditorID { get; set; }

        /// <summary>
        /// 描述 :  子项目ID
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "子项目ID")]
        public string ContractItemSubID { get; set; }

        /// <summary>
        /// 描述 :  审核员用户名
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "")]
        public string UserName { get; set; }

        /// <summary>
        /// 描述 : 组内身份名称 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "组内身份名称")]
        public string GroupIdentityName { get; set; }

        /// <summary>
        /// 描述 : 见证类型 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "见证类型")]
        public string WitnessTypeName { get; set; }

        /// <summary>
        /// 描述 :  被见证人
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "被见证人")]
        public string WitnessTypeUserName { get; set; }

        /// <summary>
        /// 描述 : 分组代码 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "分组代码")]
        public string GroupCode { get; set; }

        /// <summary>
        /// 描述 : 专业代码 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "专业代码")]
        public string ProfessionCode { get; set; }

        /// <summary>
        /// 描述 : 标准版本 
        /// 空值 : True
        /// 默认 : 
        /// </summary>
        [Display(Name = "标准版本")]
        public string ItemName { get; set; }
    }
}