//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;
using System.Linq;
using System.Text;
using SqlSugar;


namespace Meiam.System.Model
{
    ///<summary>
    ///
    ///</summary>
    [SugarTable("Cfg_AuditType")]
    public class Cfg_AuditType
    {
          public Cfg_AuditType()
          {
          }

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string ID {get;set;}

           /// <summary>
           /// 描述 : 编码 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "编码")]           
           public string AuditTypeCode {get;set;}

           /// <summary>
           /// 描述 : 名称 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "名称")]           
           public string AuditTypeName {get;set;}

           /// <summary>
           /// 描述 : 名称(英文) 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "名称(英文)")]           
           public string AuditTypeNameEN {get;set;}

           /// <summary>
           /// 描述 : 排序 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "排序")]           
           public int? SortIndex {get;set;}

           /// <summary>
           /// 描述 : 是否启用 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "是否启用")]           
           public bool? Enabled {get;set;}

           /// <summary>
           /// 描述 : 备注 
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "备注")]           
           public string Remark {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public DateTime? CreateTime {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string CreateID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string CreateName {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public DateTime? UpdateTime {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string UpdateID {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// </summary>
           [Display(Name = "")]           
           public string UpdateName {get;set;}

    }
}